```{r, include=FALSE, warning=FALSE, message=FALSE}
library(tidyverse)
library(ggtree)
library(lubridate)
library(stringdist)
library(BactDating)
knitr::opts_chunk$set(echo = FALSE)
```

```{r}
parse_mle <- function(path)
{
	result <-
		read_lines(path) %>% 
		enframe(name = NULL) %>% 
		filter(startsWith(value, "log")) %>%
		pull("value") %>%
		str_remove(".* =") %>% 
		as.numeric()
	
	list(PS = result[1], SS = result[2])
}

calc_bayes_factor <- function(root)
{
	list.files(root, "*.mle.result.log", full.names = T) %>%
		enframe(name = NULL, value = "path") %>% 
		mutate(name = basename(path)) %>%
		separate("name", c("clock", "coalescent"), extra = "drop") %>%
		bind_cols(bind_rows(lapply(.$path, parse_mle))) %>% 
		mutate(
			`BF (PS)` = PS - PS[which(clock == "str" & coalescent == "con")],
			`BF (SS)` = SS - SS[which(clock == "str" & coalescent == "con")]
		)
}

plot_chronogram <- function(tree)
{
	tip.date <-
		enframe(tree@phylo$tip.label, name = NULL) %>% 
		separate(value, c("lab", "val"), "_") %>% 
		mutate_at("val", as.Date) %>%
		pull(val)
	
	mrsd <- max(tip.date)
	lower <- with(tree@data, year(min(mrsd - years(ceiling(height + sapply(height_0.95_HPD, first))), na.rm = T)))
	upper <- with(tree@data, year(max(mrsd - years(ceiling(height - sapply(height_0.95_HPD, last))), na.rm = T)))
	
	p <-
		ggtree(tree, aes(color = rate), mrsd = mrsd, size = 1) +
		geom_range(range = "length_0.95_HPD", color = "red", alpha = 0.5, size = 1) +
		geom_nodelab(aes(x = branch, label = round(posterior, 2)), vjust = -0.5, size = 2, color = "black") +
		geom_tiplab(align = TRUE, linesize = 0.5, color = "black", size = 2) + 
		scale_color_continuous(
			low = "darkgreen", high = "red", 
			guide = guide_legend(
				label.position = "bottom", 
				label.hjust = 0.5, label.vjust = 0.5, 
				label.theme = element_text(size = 8, angle = 90)
			)
		) +
		scale_x_continuous(breaks = unique(year(tip.date)), minor_breaks = lower:upper) +
		theme_tree2() +
		theme(
			panel.grid.major.x = element_line(),
			panel.grid.minor.x = element_line(color = "grey"),
			axis.text.x = element_text(angle = 90, vjust = 0.5),
			legend.position = "none",
			text = element_text(family = "mono", size = 6)
		)
	
	ggsave(str_replace(tree@file, ".tree", ".pdf"), width = 6.5, height = 4)
	
	p
}

plot_rate_effect <- function(tree)
{
	enframe(tree@phylo$tip.label, name = NULL, value = "label") %>%
		separate(label, c("acc.ver", "date"), "_", remove = F) %>%
		mutate(date = decimal_date(ymd(date))) %>%
		mutate(date = max(date) - date) %>%
		mutate(node = nodeid(tree, label)) %>%
		merge(tree@data) %>%
		ggplot(aes(date, rate)) +
		geom_point() +
		geom_errorbar(aes(ymin = sapply(rate_0.95_HPD, first), ymax = sapply(rate_0.95_HPD, last))) +
		xlab("years in the past") +
		theme_minimal() +
		theme(axis.text.x = element_text(angle = 90, vjust = 0.5), text = element_text(family = "mono"))
}
```

```{r, fig.height=4, fig.width=10}
path <- "outbreak.xlsx"
d1 <-
	merge(openxlsx::read.xlsx(path, sheet = 1), openxlsx::read.xlsx(path, sheet = 2)) %>%
	mutate_at(c("date1", "date2"), parse_date_time, orders = c("%b %Y", "%Y")) %>%
	mutate(date2 = date2 + months(1) - days(1))

cc.1 <- read_tsv("cc-1.tsv")
cc.2 <- read_tsv("cc-2.tsv") %>% with(setNames(str_to_lower(value), str_to_lower(name)))
meta <- read_tsv("../data/meta.tsv") %>% filter(taxid %in% c(714978, 343463))

pattern <- 
	paste(cc.1$country, cc.1$official, collapse = "") %>% str_split("", simplify = T) %>% t() %>% 
	unique() %>% str_to_lower() %>% paste(collapse = "") %>% sprintf("[^%s]", .)

d2 <-
	mutate(meta, country = recode(str_remove_all(str_to_lower(country), pattern), !!!cc.2)) %>%
	mutate(country = cc.1$country[amatch(country, cc.1$country, method = "jw", maxDist = Inf)]) %>%
	merge(cc.1, by = "country", all.x = T) %>% mutate_at("collection_date", as.POSIXct) %>% 
	select(-country) %>% rename(country = code3)

ggplot() +
	geom_jitter(data = d2, aes(x = collection_date, y = country), alpha = 0.25) + 
	geom_segment(data = d1, aes(x = date1, xend = date2, y = country, yend = country, color = population), size = 3, alpha = 0.75) +
	xlab("date") +
	theme_minimal() +
	theme(legend.position = "bottom", text = element_text(family = "mono"))

ggsave("outbreak.pdf", width = 6.5, height = 2.5)
```

```{r}
dir("..", "exp-\\d+", full.names = T) %>% 
	file.path("phy-2.log") %>%
	lapply(function(path) {
		read_lines(path) %>% .[grep("Criterion:", .)] %>% enframe(name = NULL) %>% mutate(path = path)
	}) %>%
	bind_rows() %>%
	mutate(lab = str_extract(path, "exp-\\d+")) %>%
	separate(value, c("criterion", "model"), ":") %>%
	select(-path) %>%
	spread(criterion, model) %>%
	select(lab, `Bayesian Information Criterion`, everything())
```

```{r, fig.height=4, fig.width=10}
dir("..", "exp-\\d+", full.names = T) %>% 
	file.path("phy-2.treefile") %>%
	lapply(function(path) {
		tree <- read.iqtree(path)
		tip.date <- 
			str_split(tree@phylo$tip.label, "_") %>% 
			sapply(last) %>% 
			as.Date(format = "%Y-%m-%d") %>% 
			as.numeric()
		pdf(str_replace(path, ".treefile", ".signal.pdf"), 6.5, 4)
		suppressWarnings(roottotip(initRoot(tree@phylo, tip.date, 100), tip.date))
		dev.off()
	})
```

```{r}
bf <-
	dir("..", "exp-\\d+", full.names = T) %>% 
	file.path("beast") %>%
	lapply(calc_bayes_factor) %>%
	bind_rows() %>%
	mutate(lab = str_extract(path, "exp-\\d+")) %>%
	arrange(lab, desc(`BF (PS)`)) %>%
	select(lab, everything())
```

```{r}
mutate(bf, model = str_extract(path, "\\w+\\.\\w+")) %>%
	select(lab, model, PS, `BF (PS)`)
```

```{r}
select(bf, -path)
```

```{r, fig.height=10, fig.width=10}
group_by(bf, lab) %>% 
	top_n(1, `BF (PS)`) %>%
	pull(path) %>%
	str_replace("mle.*", "mcc.tree") %>%
	lapply(read.beast) %>%
	lapply(plot_chronogram)
```

```{r, fig.width=10, fig.height=4}
group_by(bf, lab) %>% 
	filter(clock == "rel") %>%
	top_n(1, `BF (PS)`) %>%
	pull(path) %>%
	str_replace("mle.*", "mcc.tree") %>%
	lapply(read.beast) %>%
	lapply(plot_rate_effect)
```
