```{r, include=FALSE, warning=FALSE, message=FALSE}
library(tidyverse)
library(ggtree)
library(lubridate)
library(BactDating)
knitr::opts_chunk$set(echo = FALSE)
```

```{r}
calc_rtt <- function(tree)
{
	tip.date <- str_split(tree@phylo$tip.label, "_") %>% sapply(last) %>% as.Date(format = "%Y-%m-%d")
	
	objective <- c("correlation", "rms", "rsquared")
	method <- c("patristic", "nNodes", "Abouheif", "sumDD")
	
	bind_rows(
		lapply(objective, function(objective) {
			x <- ape::rtt(
				tree@phylo, as.numeric(tip.date), 
				ncpu = parallel::detectCores(), 
				objective = objective
			)
			bind_rows(
				lapply(method, function(method) {
					enframe(suppressWarnings(adephylo::distRoot(x, method = method[1]))) %>% 
						mutate(date = tip.date, objective = objective, method = method) %>%
						rename(dist = value)
				})
			)
		})
	)
}

parse_mle <- function(path)
{
	result <-
		read_lines(path) %>% 
		enframe(name = NULL) %>% 
		filter(startsWith(value, "log")) %>%
		pull("value") %>%
		str_remove(".* =") %>% 
		as.numeric()
	
	list(PS = result[1], SS = result[2])
}

calc_bayes_factor <- function(root)
{
	list.files(root, "*.mle.result.log", full.names = T) %>%
		enframe(name = NULL, value = "path") %>% 
		mutate(name = basename(path)) %>%
		separate("name", c("clock", "coalescent"), extra = "drop") %>%
		bind_cols(bind_rows(lapply(.$path, parse_mle))) %>% 
		mutate(
			`BF (PS)` = PS - PS[which(clock == "str" & coalescent == "con")],
			`BF (SS)` = SS - SS[which(clock == "str" & coalescent == "con")]
		)
}

plot_chronogram <- function(tree)
{
	tip.date <-
		enframe(tree@phylo$tip.label, name = NULL) %>% 
		separate(value, c("lab", "val"), "_") %>% 
		mutate_at("val", as.Date) %>%
		pull(val)
	
	mrsd <- max(tip.date)
	lower <- with(tree@data, year(min(mrsd - years(ceiling(height + sapply(height_0.95_HPD, first))), na.rm = T)))
	upper <- with(tree@data, year(max(mrsd - years(ceiling(height - sapply(height_0.95_HPD, last))), na.rm = T)))
	
	ggtree(tree, aes(color = rate), mrsd = mrsd, size = 1) +
		geom_range(range = "length_0.95_HPD", color = "red", alpha = 0.5, size = 2) +
		geom_nodelab(aes(x = branch, label = round(posterior, 2)), vjust = -0.5, size = 3, color = "black") +
		geom_tiplab(align = TRUE, linesize = 0.5, color = "black") + 
		scale_color_continuous(
			low = "darkgreen", high = "red", 
			guide = guide_legend(
				label.position = "bottom", 
				label.hjust = 0.5, label.vjust = 0.5, 
				label.theme = element_text(size = 8, angle = 90)
			)
		) +
		scale_x_continuous(breaks = unique(year(tip.date)), minor_breaks = lower:upper) +
		theme_tree2() +
		theme(
			panel.grid.major.x = element_line(),
			panel.grid.minor.x = element_line(color = "grey"),
			axis.text.x = element_text(angle = 90, vjust = 0.5),
			legend.position = "bottom"
		)
}

plot_rate_effect <- function(tree)
{
	enframe(tree@phylo$tip.label, name = NULL, value = "label") %>%
		separate(label, c("acc.ver", "date"), "_", remove = F) %>%
		mutate_at("date", as.Date) %>%
		mutate(node = nodeid(tree, label)) %>%
		merge(tree@data) %>%
		ggplot(aes(date, rate)) +
		geom_point() +
		geom_errorbar(aes(ymin = sapply(rate_0.95_HPD, first), ymax = sapply(rate_0.95_HPD, last))) +
		theme_minimal()
}
```

```{r, fig.width=10}
# dst <-
# 	dir("..", pattern = "exp-\\d+", full.names = T) %>% 
# 	file.path("phy-2.treefile") %>%
# 	lapply(function(path) {
# 		mutate(calc_rtt(read.iqtree(path)), lab = str_extract(path, "exp-\\d+"))
# 	}) %>%
# 	bind_rows()
```

```{r, fig.height=6, fig.width=10}
dir("..", "exp-\\d+", full.names = T) %>% 
	file.path("phy-2.treefile") %>%
	lapply(function(path) {
		tree <- read.iqtree(path)
		tip.date <- 
			str_split(tree@phylo$tip.label, "_") %>% 
			sapply(last) %>% 
			as.Date(format = "%Y-%m-%d") %>% 
			as.numeric()
		suppressWarnings(roottotip(initRoot(tree@phylo, tip.date, 100), tip.date))
	})
```

```{r}
bf <-
	dir("..", full.names = T, recursive = T, include.dirs = T, pattern = "beast") %>%
	lapply(calc_bayes_factor) %>%
	bind_rows() %>%
	mutate(lab = str_extract(path, "exp-\\d+")) %>%
	arrange(lab, desc(`BF (PS)`)) %>%
	select(lab, everything())

knitr::kable(select(bf, -path))
```

```{r, fig.height=10, fig.width=10}
group_by(bf, lab) %>% 
	top_n(1, `BF (PS)`) %>%
	pull(path) %>%
	str_replace("mle.*", "mcc.tree") %>%
	lapply(read.beast) %>%
	lapply(plot_chronogram)
```

```{r, fig.width=10, fig.height=4}
group_by(bf, lab) %>% 
	filter(clock == "rel") %>%
	top_n(1, `BF (PS)`) %>%
	pull(path) %>%
	str_replace("mle.*", "mcc.tree") %>%
	lapply(read.beast) %>%
	lapply(plot_rate_effect)
```
